name: Nifty Alert

on:
  schedule:
    - cron: "0 7 * * *"    # 12:30 PM IST
    - cron: "10 7 * * *"   # 12:40 PM IST

  workflow_dispatch:
  push:
    branches:
      - main

      

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python alert.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
